WasteLess/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
   path('accounts/', include('accounts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
 
app_name = 'accounts'
 
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
    ]

main/urls.py
from django.urls import path,include
from . import views

app_name = 'main'

urlpatterns = [
    path('',views.indexview,name='index'),
    path('about',views.aboutusview,name='about'),
    path('contact',views.contactview,name='contact'),
    path('buy',views.buyview,name='buy'),
    path('productdescription/<int:pk>',views.productview,name='product'),
    path('seller',views.sellerview,name='seller'),
    path('donate',views.donateview,name='donate'),
    path('recycle',views.recycleview,name='recycle'),
    path('funds',views.fundsview,name='funds'),
    path('goods',views.goodsview,name='goods'),
    path('userprofile',views.userprofileview,name='userprofile'),
    path('delete/<int:pk>',views.deleteview,name='delete'),
    path('fundraising',views.fundraisingview,name='fundraising'),

]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

CATEGORY = (
('book','book'),
('electronic','electronic'),
('furniture','furniture'),
('clothing','clothing'),
('sport','sport'),
('stationary','stationary'),
('daily_use','daily_use'),
('other','other')
)

class Product(models.Model):   #model for the goods user post on our website
	seller = models.ForeignKey(User,on_delete=models.CASCADE)
	phone_number=models.IntegerField()
	name = models.CharField(max_length=20)
	price = models.IntegerField()
	description = models.CharField(max_length=200)
	image1 = models.ImageField(upload_to='product_image1',blank=True)
	image2 = models.ImageField(upload_to='product_image2',blank=True)
	image3 = models.ImageField(upload_to='product_image3',blank=True)
	category = models.CharField(max_length=30,choices=CATEGORY,default='book')
	address = models.CharField(max_length=100)




	def __str__(self):
		return self.name

NGO_NAME = (
('Prayaas','Prayaas'),
('Pahal','Pahal'),
('NGO1','NGO1'),
('NGO2','NGO2'),
)

class Donate(models.Model):  #model for donation of NGO
	donator = models.ForeignKey(User,on_delete=models.CASCADE)
	phone_number=models.IntegerField()
	quantity = models.CharField(max_length=300)
	description = models.CharField(max_length=200)
	image1 = models.ImageField(upload_to='product_image1',blank=True)
	image2 = models.ImageField(upload_to='product_image2',blank=True)
	image3 = models.ImageField(upload_to='product_image3',blank=True)
	NGO = models.CharField(max_length=30,choices=NGO_NAME,default='Prayaas')
	category = models.CharField(max_length=30,choices=CATEGORY,default='stationary',null=True)
	address = models.CharField(max_length=100)




	def __str__(self):
		return self.donator.username

BLOOD_GROUP =(
	('A+','A+'),
	('A-','A-'),
	('AB+','AB+'),
	('AB-','AB-'),
	('O+','O+'),
	('O-','O-')
)

# class Blood(models.Model):    #model for blood donation data
# 	donator = models.ForeignKey(User,on_delete=models.cascade)
# 	phone_number=models.IntegerField()
# 	blood_group=models.CharField(max_length=10,choices=BLOOD_GROUP)
# 	address = models.CharField(max_length=100)



# 	def __str__(self):
# 		return self.donator.username + str(self.blood_group)



# class Plasma(models.Model):    #model forplasma donation data
# 	donator = models.ForeignKey(User,on_delete=models.cascade)
# 	phone_number=models.IntegerField()
# 	blood_group=models.CharField(max_length=10,choices=BLOOD_GROUP)
# 	address = models.CharField(max_length=100)



# 	def __str__(self):
# 		return self.donator.username + str(self.blood_group)

main/forms.py
from django import forms
from django.contrib.auth import authenticate
from .models import Product



class ProductForm(forms.ModelForm):
    image1=forms.ImageField()
    image2=forms.ImageField()
    image3=forms.ImageField()

    class Meta:
        model = Product
        fields='__all__'

main/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .models import Product,Donate
from django.contrib.auth.models import User

# Create your views here.
def indexview(request):
    return render(request,'main/index.html')

def aboutusview(request):
    return render(request,'main/aboutus.html')

def contactview(request):
    return render(request,'main/contactus.html')

@login_required
def buyview(request):
	if request.method=='GET':
		products=Product.objects.all()
		return render(request,'main/buyer.html',{'products':products})

@login_required
def productview(request,pk):
	if request.method=='GET':
		product=Product.objects.filter(pk=pk).first()
		return render(request,'main/productdescription.html',{'product':product})


@login_required
def fundraisingview(request):
	return render(request,'main/fund_donation.html')

@login_required
def sellerview(request):
	if request.method=='GET':
		return render(request,'main/seller.html')
	else:
		seller=request.user
		name=request.POST.get('name')
		price=0
		description=request.POST.get('description')
		phone_number=request.POST.get('phone_number')
		category=request.POST.get('category')
		address=request.POST.get('address')
		product=Product.objects.create(seller=seller,name=name,price=price,phone_number=phone_number,description=description,
        								category=category,address=address)

		if 'image1' in request.FILES:
			image1=request.FILES['image1']
			product.image1=image1
		

		if 'image2' in request.FILES:
			image2=request.FILES['image2']
			product.image2=image2
			

		if 'image3' in request.FILES:
			image3=request.FILES['image3']
			product.image3=image3
			
		product.save()
	
		return redirect('/')





def donateview(request):
	 return render(request,'main/donate.html')


@login_required
def recycleview(request):
	if request.method=='GET':
		return render(request,'main/Recyclables.html')		
	
	else:
		donator=request.user
		quantity=request.POST.get('quantity')
		description=request.POST.get('description')
		phone_number=request.POST.get('phone_number')
		category=request.POST.get('category')
		address=request.POST.get('address')
		NGO='Prayaas'
		product=Donate.objects.create(donator=donator,quantity=quantity,phone_number=phone_number,description=description,
        								category=category,address=address,NGO=NGO)

		if 'image1' in request.FILES:
			image1=request.FILES['image1']
			product.image1=image1
		

		if 'image2' in request.FILES:
			image2=request.FILES['image2']
			product.image2=image2
			

		if 'image3' in request.FILES:
			image3=request.FILES['image3']
			product.image3=image3
			
		product.save()
		return redirect('/donate')

@login_required
def goodsview(request):
	if request.method=='GET':
		return render(request,'main/Goods.html')		
	
	else:
		donator=request.user
		quantity=request.POST.get('quantity')
		description=request.POST.get('description')
		phone_number=request.POST.get('phone_number')
		category=request.POST.get('category')
		address=request.POST.get('address')
		NGO=request.POST.get('NGO')
		product=Donate.objects.create(donator=donator,quantity=quantity,phone_number=phone_number,description=description,
        								category=category,address=address,NGO=NGO)

		if 'image1' in request.FILES:
			image1=request.FILES['image1']
			product.image1=image1
		
		if 'image2' in request.FILES:
			image2=request.FILES['image2']
			product.image2=image2
			
		if 'image3' in request.FILES:
			image3=request.FILES['image3']
			product.image3=image3
		product.save()
		return redirect('/donate')


def fundsview(request):
	 return render(request,'main/Funds.html')


@login_required
def userprofileview(request):
	if request.method=='GET':
		user=request.user
		products=Product.objects.filter(seller=user)
		return render(request,'main/userprofile.html',{'products':products,'user':user})


def deleteview(request,pk):
	if request.method=='POST':
		product=Product.objects.filter(pk=pk).first()
		product.delete()
		return redirect('/userprofile')

main/templates/main/Goods.html
{% extends 'main/base.html' %}
  {% load static %}
   {% block css%}
      <link rel ="stylesheet" href= "{% static 'css/Goods.css' %}" >
  {% endblock%} 
  {% block content %}
    
      
      <div style='min-height: 100%;position:relative;padding:0px;'>
          
            <div class="container">
                <div class="row selling">
                    <div class="offset-xl-3 col-xl-6 offset-lg-2 col-lg-8 col-md-12 col-sm-12 sell">
                        <h1>Give Goods</h1>
                         <form action="{% url 'main:goods' %}"method='POST' enctype="multipart/form-data">
                           {% csrf_token %}
                            <div class="form-group">
                                <label class="my-1 mr-2" for="inlineFormCustomSelectPref">NGO: </label>
                                <select required class="custom-select mr-sm-2" name="NGO" id="category">
                                    <option selected value="">Select NGO</option>
                                    <option value="Prayaas">Prayaas</option>
                                    <option value="Pahal">Pahal</option>
                                    <option value="NGO1">NGO1</option>
                                    <option value="clothing">NGO2</option>
                                  </select>
                            <!-- </form> -->
                        </div>
                          <div class="form-group">
                            <label for="description">Goods Description:</label>
                            <textarea type="text" class="form-control" row="1" name="description" id="productdescritpion" required placeholder="Enter good description here"></textarea>
                          </div>

                          <div class="form-group">
                                <label for="description" >Approximate Quantity:</label>
                                <input type="text" class="form-control" id="productprice" name="quantity" pattern="[0-9]{}" required placeholder="Enter approx quantity of goods">
                                <small  class="form-text text-muted">Example: 10 books OR 1kg of metal</small>

                         </div>
                            
                         <div class="form-group">
                            <label class="my-1 mr-2" for="inlineFormCustomSelectPref">Category: </label>
                            <select required class="custom-select mr-sm-2" name="category" id="category">
                                <option selected value="">Choose goods category</option>
                                <option value="books">Books</option>
                                <option value="electronic">Electronic Items</option>
                                <option value="sports">Sports</option>
                                <option value="clothing">Clothing</option>
                                <option value="stationary">Stationary</option>
                                <option value="furniture">Furniture</option>
                                <option value="furniture">Daily Use</option>
                                <option value="others">Others</option>
                              </select>
                        <!-- </form> -->
                    </div>
                        
                    <div class="form-group">
                        <label for="address">Upload Images:</label>
                        <div class="form-group">
                        <input type="file" name="image1" accept="image/*" required>
                        <input type="file" name="image2" accept="image/*">
                        <input type="file" name="image3" accept="image/*">
                        </div>
                        <small id="emailHelp" class="form-text text-muted">You may upload multiple images</small>
                    </div>
                        <div class="form-group">
                            <label for="address">Address:</label>
                            <input type="text" class="form-control" id="address" name="address" required placeholder="Enter your address here">
                            <small id="emailHelp" class="form-text text-muted">Example: Room No. 123 Boys Hostel 4, NIT Jalandhar</small>

                        </div>
                     
                        
                         <div class="form-group">
                                <label for="description">Phone Number:</label>
                                <input type="text" class="form-control" id="phonenumber" name="phone_number" pattern="[0-9]{}" required placeholder="Enter your phone number here">
                                <small id="emailHelp" class="form-text text-muted">We'll never share your phone number with anyone else.</small>
                            </div>
                            
                            <div class="form-group">
                                <div class="form-check">
                                  <input class="form-check-input" type="checkbox" value="" id="termsandcondition" required>
                                  <label class="form-check-label" for="termsandcondition">
                                   <a href="termsandconditions.html"> Agree to Terms and Conditions</a>
                                  </label>
                                </div>
                              </div>
                              <button class="btn btn-success" type="submit">Donate</button>

                         </form>
                    </div>
                </div> 
            </div>
             
        
      </div>



              
          
                
{% endblock %}

main/templates/main/Recyclables.html
{% extends 'main/base.html' %}
  {% load static %}
   {% block css%}
      <link rel ="stylesheet" href= "{% static 'css/Recyclables.css' %}" >
  {% endblock%} 
  {% block content %}
        
        
        
    
      <div style='min-height: 100%;position:relative;padding:0px;'>
          
            
                <div class="container">
                <div class="row selling">
                    <div class="offset-xl-3 col-xl-6 offset-lg-2 col-lg-8 col-md-12 col-sm-12 sell">
                        <h1>Recyclables</h1>
                         <form action="{% url 'main:recycle' %}"method='POST' enctype="multipart/form-data">
                           {% csrf_token %}

                          <div class="form-group">
                            <label for="description">Goods Description:</label>
                            <textarea type="text" class="form-control" row="1" name="description" id="productdescritpion" required placeholder="Enter good description here"></textarea>
                          </div>

                          <div class="form-group">
                                <label for="description" >Approximate Quantity:</label>
                                <input type="text" class="form-control" name="quantity" id="productprice" required placeholder="Enter approx quantity of goods">
                                <small  class="form-text text-muted">Example: 10 books OR 1kg of metal</small>

                         </div>
                            
                        
                    <div class="form-group">
                        <label for="address">Upload Images:</label>
                        <div class="form-group">
                        <input type="file" name="image1" accept="image/*" required>
                        <input type="file" name="image2" accept="image/*">
                        <input type="file" name="image3" accept="image/*">
                        </div>
                        <small id="emailHelp" class="form-text text-muted">You may upload multiple images</small>
                    </div>
                        <div class="form-group">
                            <label for="address">Address:</label>
                            <input type="text" class="form-control" id="address" name="address" required placeholder="Enter your address here">
                            <small id="emailHelp" class="form-text text-muted">Example: Room No. 123 Boys Hostel 4, NIT Jalandhar</small>

                        </div>
                     
                        
                         <div class="form-group">
                                <label for="description">Phone Number:</label>
                                <input type="text" class="form-control" id="phonenumber" name="phone_number" pattern="[0-9]{}" required placeholder="Enter your phone number here">
                                <small id="emailHelp" class="form-text text-muted">We'll never share your phone number with anyone else.</small>
                            </div>
                            
                            <div class="form-group">
                                <div class="form-check">
                                  <input class="form-check-input" type="checkbox" value="" id="termsandcondition" required>
                                  <label class="form-check-label" for="termsandcondition">
                                   <a href="termsandconditions.html"> Agree to Terms and Conditions</a>
                                  </label>

                                </div>
                              </div>
                              <button class="btn btn-primary" type="submit">Donate</button>

                         </form>
                    </div>
                </div> 
            </div>
             

          

      </div>



              
                            
  
                
  {% endblock %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang = "en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Covid Care</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        {% block css %}
        
        {% endblock %}
        <link rel="stylesheet" href="{% static 'fontawesome-free-5.10.2-web/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/home.css' %}">
        
        
    </head>
    <body>
      <div style='min-height: 100%;position:relative;padding:0px;'>
          <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-light customNav">
              <a class="navbar-brand brand" href="#">
                  <h3 onclick='location.href="{% url 'main:index' %}";'>Covid Care</h3></a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>   
            
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
              
                <ul class="navbar-nav elements">
                  <li onclick='location.href="{% url 'main:index' %}";' class="nav-item active">
                    <a class="nav-link" href="#"> <p>Home</p> <span class="sr-only">(current)</span></a>
                  </li>
                  <li onclick='location.href="{% url 'main:about' %}";' class="nav-item">
                    <a class="nav-link" href="#"><p>About Us</p></a>
                  </li>
                  <li onclick='location.href="{% url 'main:contact' %}";' class='nav-item'>
                    <a class="nav-link" href="#"><p>Contact Us</p></a>
                  </li>
                  <li style="color:white;margin-top:6px;" class="nav-item">
                     {% if user.is_authenticated %}

                     <li onclick='location.href="{% url 'main:userprofile' %}";' class="nav-item active">
                    <a class="nav-link" href="#"> <p>Hi {{user.username}}</p> </a>
                    </li>
                    <form action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <input type="submit" style=' font-size: 1.1em;color:white;   background: rgb(66, 197, 110);box-shadow: 0px 0px 0px transparent;border: 0px solid transparent;text-shadow: 0px 0px 0px transparent;margin-top: 6px' value="Log Out"></input>
                  </form>

                  


                  </li>
                   {% else %}
                  <li style="color:white;" class="nav-item">
                   <a style="color:white" class="nav-link" href="{% url 'accounts:login' %}"><p>Login/Register</p></a>
                   {% endif %}
                 </li>
                  
                </ul>
              </div>
            </nav>

            {% block content %}

            {% endblock %}

            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
              <div class="d-flex flex-column align-items-center bottom">
                  <div class = "d-flex flex-row justify-content-around align-items-center socials">
                    <i onclick="location.href = 'http://www.facebook.com';" class="fab fa-facebook"></i>
                    <i onclick="location.href = 'http://www.youtube.com';"class="fab fa-youtube"></i>
                    <i onclick="location.href = 'http://www.instagram.com';"class="fab fa-instagram"></i>
                    <i onclick="location.href = 'http://www.twitter.com';"class="fab fa-twitter"></i>
                  </div>
                  
                  <p style='color:white;font-size:0.7em;margin:10px;'>DEVELOPED BY JATIN AND NAVAL</p>
              </div>

      </div>


  
    
{% block scripts %}

      {% endblock %}


 


     

              
                            
  
                
    </body>
</html>

main/templates/main/buyer.html
  
  {% extends 'main/base.html' %}
  {% load static %}
   {% block css%}
      <link rel="stylesheet" href="{% static 'css/products.css' %}">
  {% endblock%} 
  {% block content %}
   <br>

    <div style="width:80%;margin: auto;">
      <div style='min-height: 100%;position:relative;padding:0px;'class='d-flex flex-column justify-content-center '>
       
            <div class="search">
              <button id="click" onclick="myFunction()"><img class="searchimg" src="{%static 'images/search.jpg' %}" onclick="myFunction()"></button>
              <input type="text" id="myInput"  placeholder="Search for products" title="Type in a name" >
              <button class="cli" onclick="showall()" >Show All</button>
            </div>

            <div class="cardscontain">
              <div class="notavail">
                <h1>PRODUCT NOT AVAILABLE</h1>
              </div>
              <ul class="pro">
                {% for item in products %}
                <li>  
              <div class="card ">
                <div class="prodimage">
                  <img class=" imag" src="/media/{{item.image1}} " alt="product">
            
                </div>
                <div class="description">
                    <p class="good">{{item.name}}</p> 
                    <a class="btn btn-success"  href="{% url 'main:product'  pk=item.pk %}"> Proceed</a>
                </div>
            </div>
            </li>
            {% endfor %}
            
            </ul>
            </div>
  
          </div>
      </div>
       {% endblock %}

     {% block scripts %}
      <script type="text/javascript" src="{% static 'js/search.js' %}"></script>
      
  {% endblock %}
 

       
         
                            
  
                

main/templates/main/donate.html
{% extends 'main/base.html' %}
  {% load static %}
   {% block css%}
      <link rel ="stylesheet" href= "{% static 'css/home.css' %}" >
  {% endblock%} 
  {% block content %}
        
        
        
        
    
    
      <div style='min-height: 100%;position:relative;padding:0px;'>
          


              <div class = "d-flex flex-lg-row flex-md-column flex-sm-column flex-xs-column flex-xl-row flex-grow-1 flex-shrink-0 flex-wrap justify-content-around align-items-center main">
                
                

                <div onclick='location.href="{% url 'main:seller' %}";' class="d-flex flex-column align-items-center justify-content-start card">
                    <i class="fas fa-recycle"></i>
                  <h5 style='text-align:center;'>Donate Goods </h5>
                  <hr style='margin:15px;background:#AAA;'class='break'/>
                </div>

                <div onclick='location.href="{% url 'main:funds' %}";' class="d-flex flex-column align-items-center justify-content-start card">
                        <i class="fas fa-funnel-dollar"></i>
                      <h5>Donate Funds</h5>
                      <hr style='margin:15px;background:#AAA;'class='break'/>
                    </div>

                <div onclick='location.href="{% url 'main:goods' %}";' class="d-flex flex-column align-items-center justify-content-start card">
                    <i class="fas fa-box"></i>
                  <h5>Donate Goods to NGO</h5>
                  <hr style='margin:15px;background:#AAA;'class='break'/>
            
                </div>

                <div onclick='location.href="{% url 'main:goods' %}";' class="d-flex flex-column align-items-center justify-content-start card">
                  <i class="fas fa-tint"></i>
                <h5>Donate Blood</h5>
                <hr style='margin:15px;background:#AAA;'class='break'/>
                
              </div>
               

              <div onclick='location.href="{% url 'main:goods' %}";' class="d-flex flex-column align-items-center justify-content-start card">
                <i class="fas fa-hands-helping"></i>
              <h5>Donate Plasma</h5>
              <hr style='margin:15px;background:#AAA;'class='break'/>
              
            </div>

            <div onclick='location.href="{% url 'main:fundraising' %}";' class="d-flex flex-column align-items-center justify-content-start card">
              <i class="fas fa-hand-holding-usd"></i>
            <h5>Fund Raising</h5>
            <hr style='margin:15px;background:#AAA;'class='break'/>
            
          </div>

              </div> 


             

      </div>



              
                            
  
                
  {% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
{% block css %}
<link rel ="stylesheet" href= "{% static 'css/home.css' %}">
{% endblock %}
{% block content%}

              <div class = "d-flex flex-lg-row flex-md-column flex-sm-column flex-xs-column flex-xl-row flex-grow-1 flex-shrink-0 flex-wrap justify-content-around align-items-center main">

                <div onclick='location.href = "{% url 'main:buy'%}";'  class="d-flex flex-column align-items-center justify-content-start card">
                  <i class="fas fa-shopping-cart"></i>
                  <h5>Get a Product</h5>
                  <hr style='margin:15px;background:#AAA;'class='break'/>
                  <p>Use our platform to get the list of products donated by others.</p>
                </div>
                <div onclick='location.href = "{% url 'main:seller'%}";' class="d-flex flex-column align-items-center justify-content-start card">
                  <i class="far fa-lightbulb"></i>
                  <h5>Covid Information Portal</h5>
                  <hr style='margin:15px;background:#AAA;'class='break'/>
                  <p>Read all the information related to CORONA</p>
                </div>
                <div onclick='location.href = "{% url 'main:donate'%}";'class="d-flex flex-column align-items-center justify-content-start card">
                    <i class="fas fa-donate"></i>
                  <h5>Donation Portal</h5>
                  <hr style='margin:15px;background:#AAA;'class='break'/>
                  <p>Use our platform to donate your product to 
                    hundreds of users.</p>
                </div>

               

{% endblock %}

main/templates/main/userprofile.html
{% extends 'main/base.html' %}
  {% load static %}
   {% block css%}
      <link rel ="stylesheet" href= "{% static 'css/userprofile.css' %}" >
  {% endblock%} 
  {% block content %}
      <div style='min-height: 100%;position:relative;padding:0px;'>
          
 <div class="container profilemain">
           
           
           <div class="userproducts">
               <p class="sp"><b>Products</b></p>
               <p>All the products related to your account will be visible here.</p>
               <p><b>Your Active Products:</b> </p>
               <div class="actived">
                  <br>
                  <!-- replace breaks with cards -->
                  {% for item in products%}
                  <div class="card ">
                    <div class="prodimage">
                      <img class=" imag" src="/media/{{item.image1}}" alt="product">
                
                    </div>
                    <div class="description">
                        <p class="good">{{item.name}}</p> 
                        <p style="font-size:12px;color:green;">{{item.price}}</p>
                    </div>
                    <div class="haltbut">
                        <form action="{% url 'main:delete' pk=item.pk %}" method="POST">
                            {% csrf_token %}
                      <button class="hbut" >Delete This Product</button>
                      </form>
                    </div>
                </div>
             {% endfor %}
              </div>
              
        </div>




      </div>
      {% endblock %}


              